export const ExperienceList = [
    {
        name: "Quantion",
        date: "May, 2022",
        position: "Software Engineer",
        url: "https://www.quantion.com/",
        linkedin: "https://www.linkedin.com/company/quantion/",
        text: [
            "• Developed a chatbot project for Lufthansa Group Airlines, utilizing React, JavaScript, TypeScript, CSS, and HTML to create and maintain new frontend web components for the chatbot.",
            "• Implemented backend development of an internal API for communication with different external APIs using .NET and C#, ensuring efficient communication between systems.",
            "• Utilized Scrum as a work methodology to ensure efficient and collaborative team efforts.",
            "• Conducted code reviews on pull requests, ensuring high-quality code and identifying areas for improvement.",
            "• Managed projects using Azure DevOps, ensuring that projects were delivered on time and to the client's satisfaction.",
            "• Created and maintained unit tests in .NET and Postman for API calls, ensuring the reliability of the software.",
            "• Utilized Docker containers and virtualized servers to enhance the scalability and performance of the software.",
            "• Collaborated with an international team, demonstrating strong communication and interpersonal skills.",
        ],
    },
    {
        name: "Giesecke + Devrient Mobile Security",
        date: "May, 2020",
        position: "Software Engineer",
        url: "https://www.gi-de.com/",
        linkedin: "https://www.linkedin.com/company/giesecke-devrient/",
        text: [
            "• Led frontend development efforts using JavaScript and TypeScript, utilizing Angular framework and Angular Material to build user-friendly interfaces.",
            "• Managed backend development using Java and Spring framework to ensure optimal system performance and data integrity.",
            "• Implemented Scrum as a work methodology and served as Scrum Master when required, coordinating team efforts and ensuring timely project delivery.",
            "• Conducted thorough code reviews on pull requests to maintain high-quality code and promote best practices.",
            "• Utilized Jenkins and Bitbucket for CI/CD, along with SonarQube and BlackDuck to ensure code quality and security.",
            "• Developed UI tests using Katalon and unit tests using JUnit 5 to ensure the reliability of the software.",
            "• Managed projects using Jira, ensuring that deliverables met client expectations.",
            "• Employed Docker containers and virtualized servers to enhance the scalability and performance of the software.",
            "• Collaborated remotely with an international team, demonstrating strong communication and interpersonal skills in English.",
        ],
    },
    {
        name: "VIP District",
        date: "October, 2019",
        position: "IT Operations Developer",
        url: "https://vipdistrict.com/",
        linkedin: "https://www.linkedin.com/company/vipdistrict/",
        text: [
            "• Worked as a web developer at the leading company in the management of benefit programs for groups in Spain, utilizing Java and Struts 2 to develop and maintain the web platform.",
            "• Implemented and managed unit tests using JUnit 4/5, and utilized frameworks such as Mockito to ensure the reliability of the software.",
            "• Utilized continuous integration through Jenkins to streamline the development process and improve efficiency.",
            "• Managed the MySQL database, ensuring data integrity and performance.",
            "• Conducted thorough code reviews using SonarQube, identifying areas for improvement and ensuring high-quality code.",
            "• Employed Docker containers and Git (GitFlow) to enhance the scalability and maintainability of the software.",
        ],
    },
    {
        name: "Grup T Automoció",
        date: "December, 2013",
        position: "System and Network Administrator",
        url: "https://autovivo.net/",
        linkedin: "https://www.linkedin.com/company/autovivo-grup/",
        text: [
            "• Maintained and managed the network, equipment, and telephony systems for one of the most important car dealers in the Barcelona region.",
            "• Installed and maintained Linux and Windows servers, and configured a firewall to enhance network security.",
            "• Improved storage systems by implementing NAS technology, ensuring reliable and scalable data storage.",
            "• Configured CISCO switches to optimize network performance and stability.",
            "• Monitored the network using Nagios and OP5, identifying and resolving issues promptly to minimize downtime.",
            "• Designed and configured the IP telephony network, improving communication efficiency and reducing costs.",
            "• Managed budget allocation and resource planning, ensuring that projects were completed within budget and on time.",
        ],
    },
    {
        name: "GAME Stores Iberia",
        date: "February, 2009",
        position: "Business advisor / Section chief",
        url: "https://www.game.es/",
        linkedin: "https://www.linkedin.com/company/game-stores-iberia/",
        text: [
            "• Provided commercial advice to customers in various GAME stores locations, exceeded sales targets, and managed daily operations of a store section.",
            "• Developed and implemented team training programs and provided regular feedback and coaching to team members.",
            "• Collaborated with other department managers and the senior leadership team to develop and implement store strategies and initiatives.",
            "• Maintained accurate and up-to-date records of sales, inventory, and customer interactions, analyzing data to identify trends and opportunities for improvement.",
        ],
    },
    {
        name: "LIFE Informática",
        date: "November, 2008",
        position: "IT Technician",
        url: "https://lifeinformatica.com/",
        linkedin: "https://www.linkedin.com/company/life-inform%C3%A1tica/",
        text: [
            "• Assembled and tested equipment for clients and companies, ensuring that the products met the required specifications and quality standards.",
            "• Provided technical support for equipment, including disinfection, formatting, and resolution of various issues, minimizing downtime and improving productivity.",
            "• Offered commercial advice to clients and promoted product sales, increasing revenue and improving customer satisfaction.",
            "• Diagnosed and resolved hardware and software issues, such as malware infections, operating system errors, and hardware failures, utilizing various diagnostic tools and techniques.",
            "• Conducted regular maintenance and updates on equipment to ensure optimal performance and prevent downtime, reducing the risk of data loss and system failure.",
            "• Maintained accurate records of equipment inventory, repair history, and customer interactions, ensuring that all information was up-to-date and accessible to other team members.",
            "• Collaborated with other technicians and staff to streamline processes, share knowledge, and improve overall efficiency of the company's operations.",
        ],
    },
]
